modLoader="javafml"
loaderVersion="[39,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/Kay9Unit/Bundling/issues"
[[mods]]
modId="bundling"
version="${file.jarVersion}"
displayName="Bundling"
#logoFile="examplemod.png"
#credits="Thanks for this example mod goes to Java"
authors="Kay9"
description='''
Sexy new bundles to carry and flash about.
You're not like the other girls. You can carry more random garbage in that bad boy.
'''
[[dependencies.bundling]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bundling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
